---
- name: install common packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ one_common_packages }}"

- name: deploy server
  include_tasks: server.yml
  when: one_flavor == 'server'

- name: deploy sunstone
  include_tasks: sunstone.yml
  when: one_flavor == 'sunstone'

- name: deploy worker-kvm
  include_tasks: worker-kvm.yml
  when: one_flavor == 'worker-kvm'

- name: generate and store keys
  block:
    - name: generate ssh key
      command: ssh-keygen -t ed25519 -f ~oneadmin/.ssh/id_ed25519 -N ""
      args:
        creates: ~oneadmin/.ssh/id_ed25519

    - name: fetch generated public key
      fetch:
        src: "~oneadmin/.ssh/id_ed25519.pub"
        dest: "{{ inventory_hostname_short }}_id_ed25519.pub"
        flat: yes
  when: one_flavor != 'distribute_keys'


- name: distribute public keys
  authorized_key:
    user: oneadmin
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "*_id_ed25519.pub"
  when: one_flavor == 'distribute_keys'
