---
- name: install common packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ one_common_packages }}"

- name: deploy server
  include_tasks: server.yml
  when: one_flavor == 'server'

- name: deploy sunstone
  include_tasks: sunstone.yml
  when: one_flavor == 'sunstone'

- name: deploy worker-kvm
  include_tasks: worker-kvm.yml
  when: one_flavor == 'worker-kvm'

- name: generate ssh key
  command: ssh-keygen -t ed25519 -f ~oneadmin/.ssh/id_ed25519 -N ""
  args:
    creates: ~oneadmin/.ssh/id_ed25519
  become: yes
  become_user: oneadmin

- name: fetch generated public key
  fetch:
    src: "~oneadmin/.ssh/id_ed25519.pub"
    dest: "{{ inventory_hostname_short }}_id_ed25519.pub"
    flat: yes

- name: distribute public keys
  block:
    - name: authorize all keys
      authorized_key:
        user: oneadmin
        state: present
        key: "{{ lookup('pipe', 'cat {{ item }}_id_ed25519.pub') }}"
      with_items:
        - "{{ groups['all'] }}"
  when: one_flavor == 'distribute_keys'
