---
- name: install common packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ one_common_packages }}"

- name: deploy server
  include_tasks: server.yml
  when: one_flavor == 'server'

- name: deploy sunstone
  include_tasks: sunstone.yml
  when: one_flavor == 'sunstone'

- name: deploy worker-kvm
  include_tasks: worker-kvm.yml
  when: one_flavor == 'worker-kvm'
