---
- name: install server packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ one_server_packages }}"

  #- name: create .one directory
  #file:
  #  path: "~oneadmin/.one"
  #  state: directory
  #  owner: oneadmin
  #  group: oneadmin
  #  mode: '0700'

- name: define startup password
  copy:
    dest: "~oneadmin/.one/one_auth"
    content: "oneadmin:{{ one_default_admin_password }}"
    force: yes
    mode: 0644
    owner: oneadmin
    group: oneadmin
  notify: restart_server

- name: start server service
  service:
    name: opennebula
    state: started
    enabled: yes

- name: wait for server to generate sunstone_auth
  wait_for:
    path: "~oneadmin/.one/sunstone_auth"
    state: present
    timeout: 60

- name: fetch sunstone_auth from server
  fetch:
    src: "~oneadmin/.one/sunstone_auth"
    dest: ".sunstone_auth"
    flat: true
