---
- name: install server packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ one_server_packages }}"

- name: define startup password
  copy:
    dest: "~/.one/one_auth"
    content: "{{ one_default_admin_password }}"
    force: no
  become_user: oneadmin
  notify: restart_server

- name: start server service
  service:
    name: opennebula
    state: started
    enabled: yes
