---
- name: install sunstone packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ one_sunstone_packages }}"

- name: enable sunstone service
  service:
    name: opennebula-sunstone
    state: enabled

- name: start server service
  service:
    name: opennebula-sunstone
    state: started
